@startuml
'https://plantuml.com/class-diagram

interface OnClickListener {
    void onClick();
}

class Button {
    void click()
}

class Activity {}

OnClickListener <--* Button:listeners
OnClickListener <|... Activity
Activity --> Button:button

@enduml