@startuml
'https://plantuml.com/class-diagram

interface ITopicObserver {
    + void recieveNewTopic(String s)
    + void updateTopic(int i, String s)
}

class Topic {}

class ThanhVienA {}

class ThanhVienB {}

ITopicObserver <|.. ThanhVienA
ITopicObserver <|.. ThanhVienB
Topic *--> ITopicObserver:observers
Topic <-- ThanhVienA
Topic <-- ThanhVienB
@enduml