@startuml
'https://plantuml.com/class-diagram

abstract AbstractMucDien {
    int min, max, gia;
    +{abstract} AbstractMucDien mucDienKeTiep(AbstractMucDien m)
    +{abstract} int xuLy(int soKw)
}

class MucDien {}

class MucDienCaoNhat {}

AbstractMucDien <|--- MucDien
MucDien ---> AbstractMucDien:ketiep
AbstractMucDien <|--- MucDienCaoNhat

@enduml