@startuml
'https://plantuml.com/class-diagram

interface IListenerObserver {
    +void onClick()
}

class Button {}

class Activity {}

IListenerObserver <|.. Activity
Button --> IListenerObserver:observer
Button <-- Activity:button

@enduml