@startuml
'https://plantuml.com/class-diagram

interface MyTokennize {
    + List<String> tokensize()

}

abstract class TokennizeDecorator

MyTokennize <|.. TachTu

MyTokennize <|.. TokennizeDecorator

TokennizeDecorator ---> MyTokennize : token

TokennizeDecorator <|-- RemoveStopWord
TokennizeDecorator <|-- RemovePunctuation

@enduml