@startuml
'https://plantuml.com/class-diagram

interface IListenerObserver {
    + void onClick()
}

class Button {
    click();
}

class Activity {

}

IListenerObserver <|.. Activity
Button --> IListenerObserver:observers
Button <-- Activity:button

@enduml